config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"

  resource :session
  resources :passwords, param: :token
  resources :products do
    resources :subscribers, only: [ :create ]
  end
  resource :unsubscribe, only: [ :show ]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mysite" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-light">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      
  
      <!-- Toggle Button for Mobile -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <!-- Navbar Links -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% if session[:user_id] %>
            <!-- Home Link (Visible only when logged in) -->
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <!-- Logout Button -->
            <li class="nav-item">
              <%= button_to "Log out", logout_path, method: :delete, class: "btn btn-outline-danger ms-2" %>
            </li>
          <% else %>
            <!-- Login and Sign Up Links -->
            <li class="nav-item">
              <%= link_to "Login", login_path, class: "btn btn-outline-primary me-2" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", signup_path, class: "btn btn-outline-primary me-2" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  

    <!-- Search Bar -->
<% if session[:user_id] %>
  <div class="container my-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <%= form_with url: products_path, method: :get, local: true, class: "d-flex" do |form| %>
          <%= form.text_field :query, placeholder: "Search products...", class: "form-control me-2" %>
          <%= form.submit "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>


    <!-- Flash Messages -->
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key == "notice" ? "success" : "danger" %>">
          <%= value %>
        </div>
      <% end %>
    </div>

    <!-- Main Content -->
    <main class="container my-4">
      <%= yield %>
    </main>
  </body>
</html>